{ ... }:
{
  imports = [
    ./neovim
    ./alacritty.nix
    ./bash.nix
    ./bat.nix
    ./bottom.nix
    ./chrome.nix
    ./direnv.nix
    ./discord.nix
    ./docker.nix
    ./dust.nix
    ./eza.nix
    ./fd.nix
    ./ffmpeg.nix
    ./fish.nix
    ./fzf.nix
    ./git.nix
    ./gitui.nix
    ./gopath.nix
    ./gpg.nix
    ./httpie.nix
    ./jq.nix
    ./nix-index.nix
    ./ripgrep.nix
    ./scripts.nix
    ./shell-aliases.nix
    ./starship.nix
    ./stats.nix
    ./telegram.nix
    ./tldr.nix
    ./tmux.nix
    ./yt-dlp.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
