tap "bufbuild/buf"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "fzf"
brew "protobuf"
brew "grpc"
brew "grpcurl"
brew "jmeter"
brew "jq"
brew "krb5"
brew "kubernetes-cli"
brew "lazygit"
brew "libpq"
brew "mas"
brew "node@16"
brew "neovim"
brew "node"
brew "postgresql@14"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "vite"
brew "zoxide"
brew "mongodb/brew/mongodb-community"
cask "alacritty"
cask "discord"
cask "insomnia"
cask "protonvpn"
cask "rectangle"
cask "telegram"
mas "1Blocker", id: 1365531024
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "The Unarchiver", id: 425424353
