#!/bin/sh

HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH="/opt/homebrew/bin":$PATH
export GOPATH=$HOME/Development/go
export PATH=$GOPATH/bin:$PATH
export PATH="$HOME/.local/share/neovim/bin":$PATH
