return {
  'navarasu/onedark.nvim',
  config = function()
    local colors = require('colorscheme.colors')
    require('onedark').setup({
      transparent = true,
      code_style = {
        comments = 'italic',
        keywords = 'italic',
        functions = 'italic',
        strings = 'none',
        variables = 'none',
      },
      colors = colors,
      highlights = {
        PreProc = { fg = colors.light_grey },
        ColorColumn = { bg = colors.none },
        CursorLine = { bg = colors.none },
        CursorLineNr = { fg = colors.purple, bg = colors.none },
        MatchParen = { fg = colors.cyan, bg = colors.none },
        Special = { fg = colors.cyan },
        SpecialChar = { fg = colors.cyan },

        ['@namespace'] = { fg = colors.cyan },
        ['@character'] = { fg = colors.green },
        ['@string.regex'] = { fg = colors.fg },
        ['@type.builtin'] = { fg = colors.purple },
        ['@constant.builtin'] = { fg = colors.cyan },
        ['@variable'] = { fg = colors.orange },
        ['@variable.builtin'] = { fg = colors.purple },
        ['@field'] = { fg = colors.orange },
        ['@parameter'] = { fg = colors.orange },
        ['@punctuation.special'] = { fg = colors.light_grey },

        TelescopeBorder = { fg = colors.bg_blue },
        TelescopePromptBorder = { fg = colors.bg_blue },
        TelescopeResultsBorder = { fg = colors.bg_blue },
        TelescopePreviewBorder = { fg = colors.bg_blue },
        TelescopeMatching = { fg = colors.purple },
        TelescopePromptPrefix = { fg = colors.purple },
        TelescopeSelection = { fg = colors.bg_yellow },
        TelescopeSelectionCaret = { fg = colors.purple },

        CmpItemKindSnippet = { fg = colors.light_grey },
        CmpItemKindOperator = { fg = colors.fg },
        CmpItemKindKeyword = { fg = colors.purple },
        CmpItemKindModule = { fg = colors.cyan },
        CmpItemKindConstant = { fg = colors.orange },
        CmpItemKindTypeParameter = { fg = colors.yellow },
        CmpItemKindFunction = { fg = colors.blue },
        CmpItemKindMethod = { fg = colors.blue },
        CmpItemKindConstructor = { fg = colors.yellow },
        CmpItemKindClass = { fg = colors.yellow },
        CmpItemKindInterface = { fg = colors.green },
        CmpItemKindStruct = { fg = colors.yellow },
        CmpItemKindField = { fg = colors.orange },
        CmpItemKindProperty = { fg = colors.orange },
        CmpItemKindEnum = { fg = colors.yellow },
        CmpItemKindEnumMember = { fg = colors.orange },
        CmpItemKindVariable = { fg = colors.orange },
        CmpItemKindReference = { fg = colors.orange },
        CmpItemKindEvent = { fg = colors.cyan },
        CmpItemKindUnit = { fg = colors.cyan },

        NvimTreeNormal = { fg = colors.fg },
        NvimTreeVertSplit = { fg = colors.none },
        NvimTreeEndOfBuffer = { fg = colors.light_grey },
        NvimTreeRootFolder = { fg = colors.purple },
        NvimTreeGitDirty = { fg = colors.yellow },
        NvimTreeGitNew = { fg = colors.green },
        NvimTreeGitDeleted = { fg = colors.red },
        NvimTreeSpecialFile = { fg = colors.cyan },
        NvimTreeIndentMarker = { fg = colors.bg_blue },
        NvimTreeImageFile = { fg = colors.bg_yellow },
        NvimTreeSymlink = { fg = colors.cyan },
        NvimTreeFolderName = { fg = colors.bg_blue },
      },
    })
  end,
}
