export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.homebrew/bin:$PATH"
export PATH="$HOME/.local/share/neovim/bin:$PATH"
export GOPATH="$HOME/Development/go"
export PATH="$GOPATH/bin:$PATH"
export RUSTUP_HOME="$HOME/Development/rust/.rustup"
export CARGO_HOME="$HOME/Development/rust/.cargo"
export PATH="$CARGO_HOME/bin:$PATH"
