export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export GOPATH="$HOME/Development/go"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.local/share/neovim/bin:$PATH"
export PATH="$HOME/.dotnet/tools:$PATH"
