export DOTFILES="$HOME/.dotfiles"
export CARGO_HOME="$HOME/Development/rust/.cargo"
export RUSTUP_HOME="$HOME/Development/rust/.rustup"
export RUSTC_WRAPPER="$CARGO_HOME/bin/sccache"
export GOPATH="$HOME/Development/go"
